### ISSUE TITLE
Neues bs.to update...

### ISSUE THREAD

**Issue by Smallinger** [Kartoffeleintopf/Pr0jectWatch#1]
Hey, leider funktioniert die Wiedergabe nicht mehr seid dem neuen bs.to Player update, vielleicht kannst du mal reinschauen wenn du etwas zeit findest.

**Comment by headman0** [comment]
Jup, hier das selbe.
Funktioniert so leider gar nicht mehr :(

**Comment by Ry6er** [comment]
bump
würde mich auch über einen kleinen Hotfix freuen. Hat früher echt super funktioniert, das hat mich sehr gefreut.

**Comment by TetrodoPotato** [comment]
Das Projekt weiterhin zu pflegen macht für mich keinen Sinn mehr. Zu schlecht wartbar.
